//! Cross-vendor deterministic RoPE trigonometry.
//!
//! Provenance: the integer-phase NCO from the ferrite-research
//! `ferrite-lane-abi-proof` crate. The coefficients
//! and operation order are shared with the CUDA producer patch. Every
//! operation after phase quantisation is integer arithmetic, followed by one
//! exact power-of-two conversion to `f32`.

const SIN_Q30: [i32; 8] = [0, 843_314_857, 0, -86_699_833, 0, 2_673_908, 0, -38_839];
const COS_Q30: [i32; 7] = [1_073_741_823, 0, -331_167_724, 0, 17_017_653, 0, -341_628];
const FIXED_SCALE_INV: f32 = 1.0 / 1_073_741_824.0;
// Exact binary64 value 0x1.45f306dc9c883p+29 = 2^32 / (2*pi).
const PHASE_PER_RADIAN: f64 = 683_565_275.576_431_6;
// Exact f32 bits for 500000^(-2/128). The release path is Muse-only, so the
// schedule does not depend on either platform's `powf` implementation.
const MUSE_THETA_SCALE: f32 = f32::from_bits(0x3f50_8ac1);

fn fixed_horner(coefficients: &[i32], x: u32) -> i32 {
    let mut accumulator = coefficients[coefficients.len() - 1];
    for coefficient in coefficients[..coefficients.len() - 1].iter().rev() {
        let product = (accumulator as i64) * (x as i64);
        accumulator = coefficient.wrapping_add((product >> 32) as i32);
    }
    accumulator
}

fn sincos_fixed(phase: u32) -> (f32, f32) {
    let quadrant = (phase >> 30) & 3;
    let mirrored = (phase >> 29) & 1;
    let fraction = phase & 0x1fff_ffff;
    let x = fraction << 3;
    let x = if mirrored == 1 {
        if x == 0 {
            u32::MAX
        } else {
            0u32.wrapping_sub(x)
        }
    } else {
        x
    };

    let sin_fixed = fixed_horner(&SIN_Q30, x);
    let cos_fixed = fixed_horner(&COS_Q30, x);
    let (sin_local, cos_local) = if mirrored == 1 {
        (cos_fixed, sin_fixed)
    } else {
        (sin_fixed, cos_fixed)
    };
    let sin_local = (sin_local as f32) * FIXED_SCALE_INV;
    let cos_local = (cos_local as f32) * FIXED_SCALE_INV;
    match quadrant {
        0 => (sin_local, cos_local),
        1 => (cos_local, -sin_local),
        2 => (-sin_local, -cos_local),
        _ => (-cos_local, sin_local),
    }
}

fn phase_from_angle(angle: f32) -> u32 {
    debug_assert!(angle.is_finite() && angle >= 0.0);
    (((angle as f64) * PHASE_PER_RADIAN + 0.5).floor() as u64) as u32
}

/// Build the canonical `(cos, sin)` table consumed by the strict Metal
/// rotation kernel. The iterative theta schedule intentionally matches the
/// pinned llama.cpp CUDA producer rather than recomputing each frequency from
/// a mathematically equivalent expression.
pub(crate) fn canonical_rope_table(
    context_length: usize,
    dimensions: usize,
    frequency_base: f32,
) -> Vec<f32> {
    assert_eq!(
        dimensions, 128,
        "strict RoPE NCO requires Muse head_dim=128"
    );
    assert_eq!(
        frequency_base.to_bits(),
        500_000.0f32.to_bits(),
        "strict RoPE NCO requires the pinned Muse frequency base"
    );
    let mut table = Vec::with_capacity(context_length * dimensions);
    for position in 0..context_length {
        let mut theta = position as f32;
        for _ in (0..dimensions).step_by(2) {
            let (sin, cos) = sincos_fixed(phase_from_angle(theta));
            table.push(cos);
            table.push(sin);
            theta *= MUSE_THETA_SCALE;
        }
    }
    table
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn oracle_boundaries_are_finite() {
        for phase in [
            0,
            1,
            0x1fff_ffff,
            0x2000_0000,
            0x3fff_ffff,
            0x4000_0000,
            0x7fff_ffff,
            0x8000_0000,
            0xc000_0000,
            0xffff_ffff,
        ] {
            let (sin, cos) = sincos_fixed(phase);
            assert!(sin.is_finite() && cos.is_finite());
            assert!(sin.abs() <= 1.0001 && cos.abs() <= 1.0001);
        }
    }

    #[test]
    fn muse_table_uses_cos_sin_pairs() {
        let table = canonical_rope_table(3, 128, 500_000.0);
        assert_eq!(table.len(), 384);
        for pair in table[..128].chunks_exact(2) {
            assert_eq!(pair[0].to_bits(), 0x3f80_0000);
            assert_eq!(pair[1].to_bits(), 0);
        }
        assert!(table[128..].iter().any(|value| *value != 0.0));
    }

    #[test]
    fn release_table_matches_cpp_byte_fixture() {
        // Independently generated by compiling the C++ NCO implementation
        // carried in `muser_cuda_metal_compat.patch`.  Hash the little-endian
        // table bytes, rather than approximate float values, because this is
        // the producer/consumer wire contract.
        let table = canonical_rope_table(4, 128, 500_000.0);
        let mut hash = 0xcbf2_9ce4_8422_2325u64;
        for value in table {
            for byte in value.to_bits().to_le_bytes() {
                hash ^= u64::from(byte);
                hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
            }
        }
        assert_eq!(hash, 0xec36_949c_c4f7_b428);
    }

    #[test]
    #[should_panic(expected = "pinned Muse frequency base")]
    fn strict_table_refuses_an_unpinned_frequency_schedule() {
        let _ = canonical_rope_table(1, 128, 10_000.0);
    }
}
