//! The pinned identity a node is enrolled against.
//!
//! Two files own it and nothing here invents a digest:
//!
//! - `docs/release-artifacts.json` pins the model revision and the target /
//!   DFlash GGUF SHA-256s.
//! - the container receipt (`muser.gx10-container.receipt.v1`) pins
//!   `adapter_sha256` and the exact `image_id` the producer may run.
//!
//! Tokenizer and template identities come from the canonical GGUF metadata
//! receipt generated by `muser-bench metadata`; they are never hand-entered
//! constants. Context/layout identities remain protocol ABI pins.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest as _, Sha256};

pub const LLAMA_CPP_COMMIT: &str = "89e0aa6fd362617d9073e0dafc18e41241521572";

use super::Result;

/// DFlash KV geometry the sender pins (`muser_v2_send.py` defaults).
pub const DFLASH_KV_HEADS: i64 = 8;
pub const DFLASH_HEAD_DIM: i64 = 128;

/// The producer's context bound, matching the sealed lane config.
pub const MAX_CONTEXT: i64 = 131_072;

/// Sealed lane identity. `revision` and `model_sha256` are the pin these
/// digests belong to; see the module comment.
struct SealedIdentity {
    revision: &'static str,
    model_sha256: &'static str,
    context_policy_sha256: &'static str,
    target_cache_identity_sha256: &'static str,
}

const SEALED: SealedIdentity = SealedIdentity {
    revision: "a0532f7263ee67f1e0a5f5c5fdcd50dd62fc9aa4",
    model_sha256: "7e9b74b7c8875e9e265695df9613bf6290f2392e479ce740495a129019c488d8",
    context_policy_sha256: "d2913ca9de09e906681fca2addf753b8a561aee41d4383a4f2a791e386186600",
    target_cache_identity_sha256:
        "a3bbd72fc16116322b5c9dc701f155d35349146b2af3e3b8465732b7df1eabd0",
};

#[derive(Debug, Clone, Deserialize)]
pub struct Artifact {
    pub filename: String,
    pub revision: String,
    pub url: String,
    pub bytes: u64,
    pub sha256: String,
}

#[derive(Debug, Clone, Deserialize)]
struct ReleaseArtifactsFile {
    schema: String,
    revision: String,
    artifacts: BTreeMap<String, Artifact>,
}

#[derive(Debug, Deserialize)]
struct ModelMetadataFile {
    schema: String,
    revision: String,
    target_sha256: String,
    tokenizer_hash_algorithm: String,
    tokenizer_metadata_sha256: String,
    chat_template_key: String,
    chat_template_bytes: usize,
    chat_template_sha256: String,
}

/// The pinned release, plus the sealed digests that go with it.
#[derive(Debug, Clone)]
pub struct Release {
    pub revision: String,
    pub target: Artifact,
    pub dflash: Artifact,
    pub tokenizer_sha256: String,
    pub chat_template_sha256: String,
    pub context_policy_sha256: String,
    pub target_cache_identity_sha256: String,
}

impl Release {
    pub fn load(repo_root: &Path) -> Result<Self> {
        let path = repo_root.join("docs/release-artifacts.json");
        let bytes =
            std::fs::read(&path).map_err(|error| format!("read {}: {error}", path.display()))?;
        let file: ReleaseArtifactsFile = serde_json::from_slice(&bytes)
            .map_err(|error| format!("parse {}: {error}", path.display()))?;
        let artifact = |name: &str| -> Result<Artifact> {
            let value = file
                .artifacts
                .get(name)
                .ok_or_else(|| format!("{} has no {name} artifact", path.display()))?;
            validate_sha256(name, &value.sha256)?;
            if value.revision != file.revision
                || value.bytes == 0
                || !value
                    .url
                    .contains(&format!("/resolve/{}/{}", value.revision, value.filename))
            {
                return Err(format!("{name} artifact has an invalid immutable identity"));
            }
            Ok(value.clone())
        };
        let target = artifact("target")?;
        let dflash = artifact("dflash")?;
        let metadata_path = repo_root.join("docs/release-model-metadata.json");
        let metadata: ModelMetadataFile = serde_json::from_slice(
            &std::fs::read(&metadata_path)
                .map_err(|error| format!("read {}: {error}", metadata_path.display()))?,
        )
        .map_err(|error| format!("parse {}: {error}", metadata_path.display()))?;
        if file.schema != "muser.release-artifacts.v2"
            || file.revision != SEALED.revision
            || target.sha256 != SEALED.model_sha256
        {
            return Err(format!(
                "{} pins revision {} / model {} but the sealed lane identity is {} / {}; \
                 a node cannot be enrolled against an identity no producer has agreed to",
                path.display(),
                file.revision,
                target.sha256,
                SEALED.revision,
                SEALED.model_sha256
            ));
        }
        if metadata.schema != "muser.gguf-metadata-identity.v1"
            || metadata.revision != file.revision
            || metadata.target_sha256 != target.sha256
            || metadata.tokenizer_hash_algorithm != "muser.gguf-tokenizer-metadata.v1"
            || metadata.chat_template_key != "tokenizer.chat_template"
            || metadata.chat_template_bytes != 7_167
        {
            return Err(format!(
                "{} is not bound to the pinned target GGUF identity",
                metadata_path.display()
            ));
        }
        validate_sha256("tokenizer metadata", &metadata.tokenizer_metadata_sha256)?;
        validate_sha256("chat template", &metadata.chat_template_sha256)?;
        Ok(Self {
            revision: file.revision,
            target,
            dflash,
            tokenizer_sha256: metadata.tokenizer_metadata_sha256,
            chat_template_sha256: metadata.chat_template_sha256,
            context_policy_sha256: SEALED.context_policy_sha256.into(),
            target_cache_identity_sha256: SEALED.target_cache_identity_sha256.into(),
        })
    }
}

const NATIVE_IDENTITY_PATH: &str = "scripts/gx10/vllm/native_onboarding_identity_v1.json";
const NATIVE_RUNTIME_IDENTITY_PATH: &str = "release/nvfp4-runtime-identity-v1.json";

/// Compile-time pins for the already-qualified native NVFP4 lane. The JSON
/// file supplies the complete downloadable manifest; these roots make an
/// edited manifest fail closed instead of becoming a new identity merely by
/// being present in the working tree.
struct SealedNativeIdentity {
    runtime_identity_sha256: &'static str,
    checkpoint_revision: &'static str,
    checkpoint_artifact_sha256: &'static str,
    checkpoint_receipt_sha256: &'static str,
    image_id: &'static str,
    image_receipt_sha256: &'static str,
    adapter_sha256: &'static str,
    vllm_commit: &'static str,
    overlay_receipt_sha256: &'static str,
    consumer_sha256: &'static str,
    consumer_receipt_sha256: &'static str,
    tokenizer_sha256: &'static str,
    chat_template_sha256: &'static str,
    context_policy_sha256: &'static str,
    target_cache_identity_sha256: &'static str,
    prompt_sha256: &'static str,
    rope_cache_sha256: &'static str,
    maximum_logit_absolute: f64,
    maximum_logit_mean_absolute: f64,
}

const NATIVE_SEALED: SealedNativeIdentity = SealedNativeIdentity {
    runtime_identity_sha256: "59a7e8c919745711d2af537f391e799c48d20148a7e1ecd8c9d7b7a87cf9102e",
    checkpoint_revision: "d5109a1d187c27bd1734e81844e71aa4d964e66a",
    checkpoint_artifact_sha256: "169ed694cd61d540db0c1ac0d0c088a0f6cc299f592b60cc1bc49b7ae9f4c9e1",
    checkpoint_receipt_sha256: "484e6e75361157be1822e15d386bbbbc187668179373d4a752263398f20435fa",
    image_id: "sha256:578888b29e42138a0821b68f94d952a4acc958660232e53d3ebff3ae9d933750",
    image_receipt_sha256: "163783f1f98ae341fc2425409e885b886e54a4274468a263c4476939e3327e45",
    adapter_sha256: "c49c171ffdeaa34fcff5a9be80af3256be245ed81902ce35d97cc825e197d1f7",
    vllm_commit: "6adad08767583f52eb4d2122111af0bf638ed5e6",
    overlay_receipt_sha256: "695f9ad0941181123b1bdc4eaea4db2f2249f7a18fd45217c92b328652b45e68",
    consumer_sha256: "dc9865ef9770324b1b5d7bdebc7fc6b2c9fb125084fe2461b6f5168c552193b1",
    consumer_receipt_sha256: "ccac21c54d765f62f15acf0c496b946cd129db5f6ca5f026be13cd5705e9da21",
    tokenizer_sha256: "61e73226502f8f54455555990c0000852247bbec32b107730ec544bc0b738055",
    chat_template_sha256: "114f55ebdc1804c1af371197b9fdf2d6bb925966c9dfe46b73782a71bc07965e",
    context_policy_sha256: "d2913ca9de09e906681fca2addf753b8a561aee41d4383a4f2a791e386186600",
    target_cache_identity_sha256:
        "a3bbd72fc16116322b5c9dc701f155d35349146b2af3e3b8465732b7df1eabd0",
    prompt_sha256: "149ac0d9c37c957823e53c0637b52a38f2ac601089dbda9f98eec4bc5f369030",
    rope_cache_sha256: "948949af0c4b0106dd26071d839e9643688c4c5a24f57a0fe9872d2ad49b2131",
    maximum_logit_absolute: 11.0,
    maximum_logit_mean_absolute: 1.25,
};

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct NativeCheckpointFile {
    pub filename: String,
    pub bytes: u64,
    pub sha256: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct NativeCheckpoint {
    repository: String,
    revision: String,
    directory: String,
    total_bytes: u64,
    artifact_sha256: String,
    files: Vec<NativeCheckpointFile>,
    runtime_receipt: String,
    runtime_receipt_sha256: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct NativeProducerImage {
    tag: String,
    image_id: String,
    receipt: String,
    receipt_sha256: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct NativeOverlay {
    adapter_sha256: String,
    vllm_commit: String,
    receipt: String,
    receipt_sha256: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct NativeConsumer {
    filename: String,
    bytes: u64,
    sha256: String,
    tokenizer_sha256: String,
    chat_template_sha256: String,
    context_policy_sha256: String,
    target_cache_identity_sha256: String,
    repack_receipt: String,
    repack_receipt_sha256: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct NativeRopeCache {
    schema: String,
    bytes: u64,
    sha256: String,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeFullLogitRule {
    pub mode: String,
    pub maximum_absolute: f64,
    pub maximum_mean_absolute: f64,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeQualification {
    pub schema: String,
    pub prompt_tokens: usize,
    pub output_tokens: usize,
    pub repetitions: usize,
    pub prompt_sha256: String,
    pub require_exact_tokens: bool,
    pub require_deterministic_remote_output: bool,
    pub full_logits: NativeFullLogitRule,
    pub basis: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct NativeIdentityFile {
    schema: String,
    status: String,
    source_runtime_identity_sha256: String,
    product_lane: String,
    checkpoint: NativeCheckpoint,
    producer_image: NativeProducerImage,
    vllm_overlay: NativeOverlay,
    rope_cache: NativeRopeCache,
    consumer: NativeConsumer,
    onboarding_qualification: NativeQualification,
    evidence: Vec<String>,
    ledger_basis: String,
}

/// Complete transport and execution identity for the native/text onboarding
/// lane. Hugging Face supplies bytes only; every checkpoint file remains
/// admitted by the digest list below.
#[derive(Debug, Clone)]
pub struct NativeIdentity {
    pub path: PathBuf,
    pub checkpoint_repository: String,
    pub checkpoint_revision: String,
    pub checkpoint_directory: String,
    pub checkpoint_total_bytes: u64,
    pub checkpoint_artifact_sha256: String,
    pub checkpoint_files: Vec<NativeCheckpointFile>,
    pub image_tag: String,
    pub image_id: String,
    pub adapter_sha256: String,
    pub vllm_commit: String,
    pub consumer: Artifact,
    pub tokenizer_sha256: String,
    pub chat_template_sha256: String,
    pub context_policy_sha256: String,
    pub target_cache_identity_sha256: String,
    pub rope_cache_bytes: u64,
    pub rope_cache_sha256: String,
    pub qualification: NativeQualification,
}

impl NativeIdentity {
    pub fn load(repo_root: &Path) -> Result<Self> {
        let path = repo_root.join(NATIVE_IDENTITY_PATH);
        let bytes =
            std::fs::read(&path).map_err(|error| format!("read {}: {error}", path.display()))?;
        let file: NativeIdentityFile = serde_json::from_slice(&bytes)
            .map_err(|error| format!("parse {}: {error}", path.display()))?;
        let runtime_path = repo_root.join(NATIVE_RUNTIME_IDENTITY_PATH);
        let runtime_bytes = std::fs::read(&runtime_path)
            .map_err(|error| format!("read {}: {error}", runtime_path.display()))?;
        let runtime_digest = format!("{:x}", Sha256::digest(&runtime_bytes));

        let checkpoint = &file.checkpoint;
        let producer = &file.producer_image;
        let overlay = &file.vllm_overlay;
        let consumer = &file.consumer;
        let rope_cache = &file.rope_cache;
        let qualification = &file.onboarding_qualification;
        for (label, digest) in [
            ("checkpoint artifact", checkpoint.artifact_sha256.as_str()),
            (
                "checkpoint runtime receipt",
                checkpoint.runtime_receipt_sha256.as_str(),
            ),
            ("producer receipt", producer.receipt_sha256.as_str()),
            ("adapter", overlay.adapter_sha256.as_str()),
            ("overlay receipt", overlay.receipt_sha256.as_str()),
            ("consumer", consumer.sha256.as_str()),
            (
                "consumer repack receipt",
                consumer.repack_receipt_sha256.as_str(),
            ),
            ("tokenizer", consumer.tokenizer_sha256.as_str()),
            ("chat template", consumer.chat_template_sha256.as_str()),
            ("context policy", consumer.context_policy_sha256.as_str()),
            (
                "target cache identity",
                consumer.target_cache_identity_sha256.as_str(),
            ),
            ("qualification prompt", qualification.prompt_sha256.as_str()),
            ("RoPE cache", rope_cache.sha256.as_str()),
            (
                "source runtime identity",
                file.source_runtime_identity_sha256.as_str(),
            ),
        ] {
            validate_sha256(label, digest)?;
        }
        let image_digest = producer
            .image_id
            .strip_prefix("sha256:")
            .ok_or_else(|| "native producer image must use an exact sha256 ID".to_string())?;
        validate_sha256("native producer image", image_digest)?;

        if file.schema != "muser.native-onboarding-identity.v1"
            || file.status != "frozen"
            || file.source_runtime_identity_sha256 != NATIVE_SEALED.runtime_identity_sha256
            || runtime_digest != NATIVE_SEALED.runtime_identity_sha256
            || file.product_lane.is_empty()
            || file.evidence.is_empty()
            || file.ledger_basis.is_empty()
            || checkpoint.repository != "RedHatAI/Muse-Glimmer-30B-NVFP4"
            || checkpoint.revision != NATIVE_SEALED.checkpoint_revision
            || checkpoint.artifact_sha256 != NATIVE_SEALED.checkpoint_artifact_sha256
            || checkpoint.runtime_receipt_sha256 != NATIVE_SEALED.checkpoint_receipt_sha256
            || producer.image_id != NATIVE_SEALED.image_id
            || producer.receipt_sha256 != NATIVE_SEALED.image_receipt_sha256
            || overlay.adapter_sha256 != NATIVE_SEALED.adapter_sha256
            || overlay.vllm_commit != NATIVE_SEALED.vllm_commit
            || overlay.receipt_sha256 != NATIVE_SEALED.overlay_receipt_sha256
            || consumer.sha256 != NATIVE_SEALED.consumer_sha256
            || consumer.repack_receipt_sha256 != NATIVE_SEALED.consumer_receipt_sha256
            || consumer.tokenizer_sha256 != NATIVE_SEALED.tokenizer_sha256
            || consumer.chat_template_sha256 != NATIVE_SEALED.chat_template_sha256
            || consumer.context_policy_sha256 != NATIVE_SEALED.context_policy_sha256
            || consumer.target_cache_identity_sha256 != NATIVE_SEALED.target_cache_identity_sha256
            || qualification.prompt_sha256 != NATIVE_SEALED.prompt_sha256
            || rope_cache.sha256 != NATIVE_SEALED.rope_cache_sha256
        {
            return Err(format!(
                "{} differs from the compiled native NVFP4 identity roots",
                path.display()
            ));
        }
        if checkpoint.runtime_receipt.is_empty()
            || producer.tag.is_empty()
            || producer.receipt.is_empty()
            || overlay.receipt.is_empty()
            || consumer.repack_receipt.is_empty()
            || checkpoint.directory.is_empty()
            || checkpoint.directory.contains('/')
            || consumer.filename.is_empty()
            || consumer.filename.contains('/')
            || consumer.bytes == 0
            || checkpoint.files.is_empty()
            || rope_cache.schema != "muser.vllm-rope-cache.v2"
            || rope_cache.bytes != 67_108_864
        {
            return Err("native NVFP4 identity has an empty or unsafe artifact field".into());
        }

        let mut files = checkpoint.files.clone();
        files.sort_by(|left, right| left.filename.cmp(&right.filename));
        if files != checkpoint.files {
            return Err("native checkpoint manifest must be sorted by filename".into());
        }
        let mut total = 0u64;
        let mut aggregate = Sha256::new();
        let mut previous: Option<&str> = None;
        for item in &files {
            if item.filename.is_empty()
                || item.filename.contains('/')
                || item.filename.contains("..")
                || item.bytes == 0
                || previous == Some(item.filename.as_str())
            {
                return Err("native checkpoint manifest has an unsafe or duplicate file".into());
            }
            validate_sha256("native checkpoint file", &item.sha256)?;
            total = total
                .checked_add(item.bytes)
                .ok_or_else(|| "native checkpoint total byte count overflow".to_string())?;
            aggregate.update(item.filename.as_bytes());
            aggregate.update([0]);
            aggregate.update(item.bytes.to_string().as_bytes());
            aggregate.update([0]);
            aggregate.update(item.sha256.as_bytes());
            aggregate.update(b"\n");
            previous = Some(&item.filename);
        }
        if total != checkpoint.total_bytes
            || format!("{:x}", aggregate.finalize()) != checkpoint.artifact_sha256
        {
            return Err("native checkpoint manifest aggregate differs from its pinned root".into());
        }
        if qualification.schema != "muser.native-text-onboarding.v1"
            || qualification.prompt_tokens != 2_048
            || qualification.output_tokens != 256
            || qualification.repetitions != 3
            || !qualification.require_exact_tokens
            || !qualification.require_deterministic_remote_output
            || qualification.full_logits.mode != "bounded-drift"
            || !qualification.full_logits.maximum_absolute.is_finite()
            || !qualification.full_logits.maximum_mean_absolute.is_finite()
            || qualification.full_logits.maximum_absolute <= 0.0
            || qualification.full_logits.maximum_mean_absolute <= 0.0
            || qualification.full_logits.maximum_absolute != NATIVE_SEALED.maximum_logit_absolute
            || qualification.full_logits.maximum_mean_absolute
                != NATIVE_SEALED.maximum_logit_mean_absolute
            || qualification.basis.is_empty()
        {
            return Err("native onboarding qualification rule is invalid".into());
        }

        Ok(Self {
            path,
            checkpoint_repository: checkpoint.repository.clone(),
            checkpoint_revision: checkpoint.revision.clone(),
            checkpoint_directory: checkpoint.directory.clone(),
            checkpoint_total_bytes: checkpoint.total_bytes,
            checkpoint_artifact_sha256: checkpoint.artifact_sha256.clone(),
            checkpoint_files: files,
            image_tag: producer.tag.clone(),
            image_id: producer.image_id.clone(),
            adapter_sha256: overlay.adapter_sha256.clone(),
            vllm_commit: overlay.vllm_commit.clone(),
            consumer: Artifact {
                filename: consumer.filename.clone(),
                revision: checkpoint.revision.clone(),
                // The repack is currently operator-supplied. This empty URL
                // is deliberate: node onboarding never invents a download
                // location for a 19.6 GB consumer artifact.
                url: String::new(),
                bytes: consumer.bytes,
                sha256: consumer.sha256.clone(),
            },
            tokenizer_sha256: consumer.tokenizer_sha256.clone(),
            chat_template_sha256: consumer.chat_template_sha256.clone(),
            context_policy_sha256: consumer.context_policy_sha256.clone(),
            target_cache_identity_sha256: consumer.target_cache_identity_sha256.clone(),
            rope_cache_bytes: rope_cache.bytes,
            rope_cache_sha256: rope_cache.sha256.clone(),
            qualification: qualification.clone(),
        })
    }

    pub fn checkpoint_artifact(&self, file: &NativeCheckpointFile) -> Artifact {
        Artifact {
            filename: file.filename.clone(),
            revision: self.checkpoint_revision.clone(),
            url: format!(
                "https://huggingface.co/{}/resolve/{}/{}?download=true",
                self.checkpoint_repository, self.checkpoint_revision, file.filename
            ),
            bytes: file.bytes,
            sha256: file.sha256.clone(),
        }
    }
}

/// The subset of `muser.gx10-container.receipt.v1` the pipeline reads. The
/// checks below are the same ones `muser_prefilld.py:load_config` makes
/// before it arms an exporter identity — refusing here means the operator
/// learns at `deploy` time, not at first prefill.
#[derive(Debug, Clone, Deserialize)]
pub struct ContainerReceipt {
    pub schema: String,
    pub status: String,
    pub architecture: String,
    pub image_id: String,
    pub image_tag: String,
    pub adapter_sha256: String,
    pub cuda_matmul: String,
    pub entrypoint: Vec<String>,
    pub source_commit: String,
    #[serde(skip)]
    pub path: PathBuf,
}

pub const EXPORT_BINARY: &str = "/opt/muser/bin/spark_kv_export";
pub const RECEIPT_SCHEMA: &str = "muser.gx10-container.receipt.v1";
pub const IMAGE_TAG_PREFIX: &str = "muser-gx10-prefill:";

/// Where `build_gx10_container.py`'s receipts live. Explicit operator
/// input via `MUSER_RECEIPTS_DIR` — there is no implicit default root.
pub fn receipts_dir() -> std::path::PathBuf {
    std::env::var_os("MUSER_RECEIPTS_DIR")
        .map(std::path::PathBuf::from)
        .expect("MUSER_RECEIPTS_DIR must name the container-receipts root")
}

impl ContainerReceipt {
    pub fn load(path: &Path) -> Result<Self> {
        let bytes =
            std::fs::read(path).map_err(|error| format!("read {}: {error}", path.display()))?;
        let mut receipt: Self = serde_json::from_slice(&bytes)
            .map_err(|error| format!("parse {}: {error}", path.display()))?;
        receipt.path = path.to_path_buf();
        receipt.validate()?;
        Ok(receipt)
    }

    fn validate(&self) -> Result<()> {
        if self.schema != RECEIPT_SCHEMA
            || self.status != "built"
            || self.architecture != "arm64"
            || self.entrypoint != [EXPORT_BINARY]
            || !matches!(
                self.cuda_matmul.as_str(),
                "default" | "force-cublas" | "force-mmq"
            )
        {
            return Err(format!(
                "{} is not a built arm64 sealed-exporter receipt",
                self.path.display()
            ));
        }
        let id = self
            .image_id
            .strip_prefix("sha256:")
            .ok_or_else(|| "container image must be addressed by exact image ID".to_string())?;
        validate_sha256("image_id", id)?;
        validate_sha256("adapter_sha256", &self.adapter_sha256)?;
        if self.source_commit.len() != 40
            || !self.source_commit.bytes().all(|b| b.is_ascii_hexdigit())
        {
            return Err("receipt source_commit is not an exact 40-hex commit".into());
        }
        Ok(())
    }

    /// Newest producer receipt in `dir`, by modification time. "Producer"
    /// means the receipt's own image tag, not its filename.
    pub fn newest(dir: &Path) -> Result<Self> {
        let entries =
            std::fs::read_dir(dir).map_err(|error| format!("read {}: {error}", dir.display()))?;
        let mut best: Option<(std::time::SystemTime, PathBuf)> = None;
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|value| value.to_str()) != Some("json") {
                continue;
            }
            let Ok(receipt) = Self::load(&path) else {
                continue;
            };
            if !receipt.image_tag.starts_with(IMAGE_TAG_PREFIX) {
                continue;
            }
            let Ok(modified) = entry.metadata().and_then(|meta| meta.modified()) else {
                continue;
            };
            if best.as_ref().is_none_or(|(best, _)| modified > *best) {
                best = Some((modified, path));
            }
        }
        let (_, path) = best.ok_or_else(|| {
            format!(
                "no {IMAGE_TAG_PREFIX}* receipt under {} — pass --container-receipt",
                dir.display()
            )
        })?;
        Self::load(&path)
    }
}

pub fn validate_sha256(label: &str, value: &str) -> Result<()> {
    if value.len() != 64
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Err(format!("{label} must be a lowercase SHA-256"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn digests_must_be_lowercase_hex() {
        assert!(validate_sha256("x", &"a".repeat(64)).is_ok());
        assert!(validate_sha256("x", &"A".repeat(64)).is_err());
        assert!(validate_sha256("x", &"a".repeat(63)).is_err());
    }

    #[test]
    fn the_repo_release_pin_matches_the_sealed_lane_identity() {
        // The whole enrolment path hangs off this equality; a silent drift
        // would mint handoff configs no producer can admit.
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("workspace root");
        let release = Release::load(root).expect("release-artifacts.json must load");
        assert_eq!(release.revision, SEALED.revision);
        assert_eq!(release.target.sha256, SEALED.model_sha256);
        assert_eq!(release.dflash.sha256.len(), 64);
    }

    #[test]
    fn the_repo_native_identity_matches_its_compiled_roots() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("workspace root");
        let identity = NativeIdentity::load(root).expect("native runtime identity must load");
        let cross_vendor_math: serde_json::Value = serde_json::from_slice(
            &std::fs::read(root.join("release/gx10-cross-vendor-math-v1.json"))
                .expect("cross-vendor math identity must be readable"),
        )
        .expect("cross-vendor math identity must parse");
        assert_eq!(
            identity.checkpoint_artifact_sha256,
            NATIVE_SEALED.checkpoint_artifact_sha256
        );
        assert_eq!(identity.image_id, NATIVE_SEALED.image_id);
        assert_eq!(identity.consumer.sha256, NATIVE_SEALED.consumer_sha256);
        assert_eq!(identity.rope_cache_sha256, NATIVE_SEALED.rope_cache_sha256);
        assert_eq!(
            cross_vendor_math["qualification"]["rope_cache_sha256"],
            identity.rope_cache_sha256
        );
        assert_eq!(identity.checkpoint_files.len(), 12);
        assert_eq!(identity.qualification.repetitions, 3);
    }
}
